### ISSUE TITLE
There are no annotations for Minecraft Story Mode Season 2 Episodes 3-5

### ISSUE THREAD

**Issue by Shaymix** [bgbennyboy/Telltale-Speech-Extractor#1]
Hello, I want to inform you that I noticed that there are no annotations for Minecraft Story Mode Season 2 Episodes 3-5 on the Annotations file of the Telltale Speech Extractor.
Can you fix that?

**Comment by bgbennyboy** [comment]
Whoops, looks like I forgot to include all the new annotations. I'll upload a fix tonight

**Comment by bgbennyboy** [comment]
[Fixed](https://quickandeasysoftware.net/telltale-speech-extractor-bugfix) thank you.
